#!/usr/bin/env bash
# refresh_sb_context.sh — pull canonical Second Brain content into <repo>/.ai/context/sb-derived/
#
# The SB project to mirror is read from <repo>/.ai/sb-project-link (single line:
# the SB project slug, e.g. "sample-bot"). The SB clone path comes from the
# SECOND_BRAIN_PATH env var (default: ~/AcuityTech/Second Brain).
#
# Idempotent: re-running overwrites derived files with a fresh banner.
# Fail-soft: missing SB clone, missing project, or missing link file produce
# clear warnings and a non-fatal exit when --soft is passed; otherwise exit 1.

set -uo pipefail

PROG="${0##*/}"

usage() {
  cat <<EOF
Usage: ${PROG} [--help] [--soft] [<repo-path>]

Pull the brain, specs, ratified decisions, and sources index for an SB project
into <repo-path>/.ai/context/sb-derived/. The SB project slug is read from
<repo-path>/.ai/sb-project-link.

Arguments:
  <repo-path>   Repo to refresh. Defaults to current working directory.

Options:
  --help        Show this help and exit.
  --soft        Exit 0 (with a warning) when SB or the link file is missing.
                Useful for bootstrap flows that should not fail when SB is
                unreachable on the current machine.

Environment:
  SECOND_BRAIN_PATH   Path to the Second Brain clone.
                      Default: \$HOME/AcuityTech/Second Brain

Files:
  .ai/sb-project-link               Single line: SB project slug to mirror.
  .ai/context/sb-derived/           Generated; gitignored by default.
  .ai/context/sb-derived/.gitignore Ignores everything under this directory.
EOF
}

SOFT=0
REPO_PATH=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --soft)    SOFT=1; shift ;;
    --)        shift; REPO_PATH="${1:-}"; shift || true; break ;;
    -*)        echo "[refresh_sb_context] unknown option: $1" >&2; usage >&2; exit 2 ;;
    *)         REPO_PATH="$1"; shift ;;
  esac
done

REPO_PATH="${REPO_PATH:-$PWD}"

if [[ ! -d "${REPO_PATH}" ]]; then
  echo "[refresh_sb_context] repo path not found: ${REPO_PATH}" >&2
  exit 1
fi

REPO_PATH="$(cd "${REPO_PATH}" && pwd)"
LINK_FILE="${REPO_PATH}/.ai/sb-project-link"
DERIVED_DIR="${REPO_PATH}/.ai/context/sb-derived"
SB_PATH="${SECOND_BRAIN_PATH:-${HOME}/AcuityTech/Second Brain}"

soft_exit() {
  local msg="$1"
  if [[ "${SOFT}" -eq 1 ]]; then
    echo "[refresh_sb_context] WARN ${msg} (soft mode — continuing)" >&2
    exit 0
  fi
  echo "[refresh_sb_context] ERROR ${msg}" >&2
  exit 1
}

if [[ ! -d "${REPO_PATH}/.ai" ]]; then
  soft_exit "no .ai/ directory at ${REPO_PATH} — run bootstrap_real_repo.sh first"
fi

if [[ ! -f "${LINK_FILE}" ]]; then
  soft_exit "missing ${LINK_FILE} — write the SB project slug into it (e.g. 'sample-bot')"
fi

PROJECT_SLUG="$(head -n1 "${LINK_FILE}" | tr -d '[:space:]')"
if [[ -z "${PROJECT_SLUG}" ]]; then
  soft_exit "${LINK_FILE} is empty"
fi

if [[ ! -d "${SB_PATH}" ]]; then
  soft_exit "Second Brain not found at: ${SB_PATH} (set SECOND_BRAIN_PATH to override)"
fi

PROJECT_DIR="${SB_PATH}/01-Projects/${PROJECT_SLUG}"
if [[ ! -d "${PROJECT_DIR}" ]]; then
  echo "[refresh_sb_context] project '${PROJECT_SLUG}' not found under ${SB_PATH}/01-Projects/" >&2
  echo "[refresh_sb_context] available projects:" >&2
  if [[ -d "${SB_PATH}/01-Projects" ]]; then
    (cd "${SB_PATH}/01-Projects" && ls -1d */ 2>/dev/null | sed 's:/$::' | sed 's/^/  - /' >&2)
  fi
  soft_exit "SB project missing"
fi

ISO_TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

mkdir -p "${DERIVED_DIR}"

# Always (re)write the gitignore template so the directory stays uncommitted.
cat > "${DERIVED_DIR}/.gitignore" <<'GIEOF'
# This directory is regenerated by scripts/refresh_sb_context.sh.
# Treat it as a build artifact: do not commit its contents.
*
!.gitignore
GIEOF

write_with_banner() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "${dst}")"
  {
    printf '<!-- DERIVED FROM Second Brain %s at %s; DO NOT EDIT — re-run scripts/refresh_sb_context.sh to refresh -->\n\n' \
      "${src}" "${ISO_TS}"
    cat "${src}"
  } > "${dst}"
}

COPIED=0
SKIPPED=0

# 1. Project brain
BRAIN_SRC="${PROJECT_DIR}/.opencode/skill/${PROJECT_SLUG}-brain.md"
if [[ -f "${BRAIN_SRC}" ]]; then
  write_with_banner "${BRAIN_SRC}" "${DERIVED_DIR}/brain.md"
  COPIED=$((COPIED+1))
  echo "  [copy] brain.md"
else
  echo "  [skip] brain.md (no ${BRAIN_SRC})"
  SKIPPED=$((SKIPPED+1))
fi

# 2. Specs
SPECS_SRC_DIR="${PROJECT_DIR}/04-specs"
SPECS_DST_DIR="${DERIVED_DIR}/specs"
rm -rf "${SPECS_DST_DIR}"
if [[ -d "${SPECS_SRC_DIR}" ]]; then
  while IFS= read -r -d '' f; do
    rel="${f#${SPECS_SRC_DIR}/}"
    write_with_banner "${f}" "${SPECS_DST_DIR}/${rel}"
    COPIED=$((COPIED+1))
  done < <(find "${SPECS_SRC_DIR}" -type f -name '*.md' -print0)
  echo "  [copy] specs/ ($(find "${SPECS_DST_DIR}" -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ') file(s))"
else
  echo "  [skip] specs/ (no ${SPECS_SRC_DIR})"
  SKIPPED=$((SKIPPED+1))
fi

# 3. Decisions
DEC_SRC_DIR="${PROJECT_DIR}/03-decisions"
DEC_DST_DIR="${DERIVED_DIR}/decisions"
rm -rf "${DEC_DST_DIR}"
if [[ -d "${DEC_SRC_DIR}" ]]; then
  while IFS= read -r -d '' f; do
    rel="${f#${DEC_SRC_DIR}/}"
    write_with_banner "${f}" "${DEC_DST_DIR}/${rel}"
    COPIED=$((COPIED+1))
  done < <(find "${DEC_SRC_DIR}" -type f -name 'DR-*.md' -print0)
  echo "  [copy] decisions/ ($(find "${DEC_DST_DIR}" -type f -name 'DR-*.md' 2>/dev/null | wc -l | tr -d ' ') file(s))"
else
  echo "  [skip] decisions/ (no ${DEC_SRC_DIR})"
  SKIPPED=$((SKIPPED+1))
fi

# 4. Sources index
SRC_INDEX="${PROJECT_DIR}/01-sources/_index.md"
if [[ -f "${SRC_INDEX}" ]]; then
  write_with_banner "${SRC_INDEX}" "${DERIVED_DIR}/sources-index.md"
  COPIED=$((COPIED+1))
  echo "  [copy] sources-index.md"
else
  echo "  [skip] sources-index.md (no ${SRC_INDEX})"
  SKIPPED=$((SKIPPED+1))
fi

echo "[refresh_sb_context] project=${PROJECT_SLUG} sb=${SB_PATH} copied=${COPIED} skipped=${SKIPPED}"
echo "[refresh_sb_context] output: ${DERIVED_DIR}"
